# Introduction to Numpy
### Click the link below to run this on Google Colab
https://colab.research.google.com/github/brightmaraba/data-analysis/blob/main/work.ipynb

In [1]:
import numpy as np
import sys

In [2]:
# Basic Numpy Arrays
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
# Index of np arrays start from 0
a[0], a[1]

(1, 2)

In [5]:
# Slicing np arrays
# Whole array
a[:], a[0:]

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [6]:
# Slicing array[start, stop, step]
a[1:3] # Start from index 1 stop at index 3 (value of index 3 not included)

array([2, 3])

In [7]:
# -ve indexing begins at end of array
a[1:-1] # Start at index one end at index -1 (Again, value of end index is not included)

array([2, 3, 4, 5, 6, 7, 8])

In [9]:
# Slicing with steps
a[::2] # [::2] - Whole array but skips of 2

array([1, 3, 5, 7, 9])

In [10]:
# Return array values using their index
b = np.array([1,2,3,4,5,6])
b[0], b[3], b[5]

(1, 4, 6)

In [11]:
# Above operation can be done once
b[[0, 2, -1]]

array([1, 3, 6])